language: crystal
os: linux
services:
  - postgresql
script:
  - crystal tool format spec src --check
  - crystal spec
  - crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  project_name: great_idea
  on:
    branch: master
  local_dir: docs
cache:
  directories:
    - bin/lucky
    - lib
    - .shards
