name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: crystallang/crystal
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

    steps:
    # TODO - should move into custom docker image
    - name: Install postgres tools
      run: |
        apt-get update
        apt-get install -y postgresql postgresql-contrib

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache shards
      uses: actions/cache@v1
      env:
        cache-name: cache-shards
      with:
        path: lib
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/shard.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install deps
      run: shards install

    - name: Check file formatting
      run: crystal tool format spec src --check

    - name: Run tests
      run: crystal spec

    - name: Build docs
      run: crystal docs

  # TODO
  # deploy-docs:
  #   runs-on: ubuntu-latest
