name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: crystallang/crystal
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

    steps:
    - name: Install base deps
      # From luckyframework/avram Dockerfile
      run: |
        apt-get update && \
        apt-get install -y libgconf-2-4 curl libreadline-dev && \
        # postgres 11 installation
        curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
        echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" | tee /etc/apt/sources.list.d/postgres.list && \
        apt-get update && \
        apt-get install -y postgresql-11 && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

    - name: Install rsync
      run: |
        apt-get update && \
        apt-get install -y rsync

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Cache shards
      uses: actions/cache@v1
      env:
        cache-name: cache-shards
      with:
        path: lib
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/shard.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install deps
      run: shards install

    - name: Check file formatting
      run: crystal tool format spec src --check

    - name: Run tests
      run: crystal spec

    - name: Build docs
      run: crystal docs

    - name: Deploy docs
      if: github.ref == 'refs/heads/master' # Only run if branch is master
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
