name: Crystal CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: crystallang/crystal
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
#       with:
#         persist-credentials: false

    - name: Install deps
      run: shards install

    - name: Create Lucky CLI
      run: script/create_lucky.sh

    - name: Verify postgres connection
      run: |
        apt-get update
        apt-get install -y postgresql postgresql-contrib
        bin/lucky db.verify_connection

    - name: Check file formatting
      run: crystal tool format spec src --check

    - name: Run tests
      run: crystal spec

    - name: Build docs
      run: crystal docs

# TODO - just using travis ci for docs deployments for now
#     - name: Deploy docs
#       if: github.ref == 'refs/heads/master' # only run if branch is master
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: docs
